---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos7

suites:
  - name: default
    run_list:
      - recipe[guacamole::default]
      - recipe[guacamole::00_prerequisites]
      - recipe[guacamole::01_staging]
      - recipe[guacamole::02_install]
      - recipe[guacamole::03_configure]
      - recipe[guacamole::04_finalise]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
